export * as HomeIcon from './home.svg';
export * as DashboardIcon from './dashboard.svg';
export * as ProjectIcon from './projects.svg';
export * as TaskIcon from './task.svg';
export * as ReportingIcon from './reporting.svg';
export * as UserIcon from './user.svg';
export * as SupportIcon from './support.svg';
export * as SettingsIcon from './settings.svg';
export * as  Logo from './logo.svg'